'use client';
import {useEffect,useState} from 'react';
import {Flag,Radio,Download,Upload,Check,X,RefreshCw,Info,FileJson} from 'lucide-react';
import {type Network,type Position,isFresh,readLocal,writeLocal} from '../lib/mobility';
import {IS_LOCAL_DEMO,request,listRecords,downloadJSON,getPositions} from '../lib/api';
import {RouteBadge} from './Travel';
type Report={id:string;route_id:string;category:string;description:string;status:string};
export type AdminSection='data'|'reports'|'gps';
export default function Admin({section,network,notify,onNetwork,onPending}:{section:AdminSection;network:Network;notify:(s:string)=>void;onNetwork:(n:Network)=>void;onPending?:(count:number)=>void}){
 const tab=section;
 const [reports,setReports]=useState<Report[]>([]),[positions,setPositions]=useState<Position[]>([]),[draft,setDraft]=useState(''),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const refresh=async()=>{setError('');try{const items=await listRecords<Report>('reports');setReports(items);onPending?.(items.filter(r=>r.status==='pending').length);setPositions(await getPositions())}catch(e){setError((e as Error).message)}};
 useEffect(()=>{refresh()},[]);
 const decide=async(r:Report,status:string)=>{try{if(IS_LOCAL_DEMO){const next=reports.map(item=>item.id===r.id?{...item,status}:item);writeLocal('juliaca-reports',next);setReports(next)}else{await request(`/admin/reports/${r.id}`,{status},'PATCH');await refresh()}notify(status==='reviewed'?'Reporte revisado. Corrige la ruta por separado si corresponde.':'Reporte descartado.')}catch(e){setError((e as Error).message)}};
 const importNetwork=async()=>{setBusy(true);setError('');try{const net=JSON.parse(draft) as Network;if(!Array.isArray(net.routes)||!Array.isArray(net.stops)||net.routes.length===0||net.stops.length<2)throw new Error('Se requieren listas de rutas y puntos.');const ids=new Set(net.stops.map(s=>s.id));if(net.routes.some(r=>!Array.isArray(r.stops)||!Array.isArray(r.inbound)||r.stops.length<2||!r.stops.concat(r.inbound).every(id=>ids.has(id))))throw new Error('Hay rutas sin puntos o referencias inexistentes.');if(IS_LOCAL_DEMO)throw new Error('La importación de rutas reales requiere conectar el servidor. Puedes exportar y preparar el archivo aquí.');await request('/admin/network/import',net);onNetwork(await request<Network>('/network'));setEditing(false);notify('Red importada. Se conservó una versión anterior.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <main className="workspace"><div className="admin-toolbar"><p className="muted">{tab==='data'?'Revisa fuentes y cambios antes de publicarlos en la red pública.':tab==='reports'?'Los reportes no se publican automáticamente ni modifican rutas.':'Una posición antigua no se presenta como seguimiento actual.'}</p><span className="admin-toolbar-spacer"/><button className="secondary" onClick={refresh}><RefreshCw size={16}/>Actualizar</button></div>
 {IS_LOCAL_DEMO&&<div className="data-note" style={{marginBottom:24}}><Info size={17}/><span>Administración de demostración. Reportes, propuestas y observaciones se guardan solo en este navegador. La red de ejemplo permanece protegida.</span></div>}
 <>
 {tab==='data'&&<section className="surface"><div className="surface-head"><div><h2>Inventario de recorridos</h2><p className="muted">{network.routes.filter(r=>!r.verified_at).length} rutas pendientes de verificar</p></div><div className="inline-actions"><button className="secondary" onClick={()=>downloadJSON('juliaca-red.json',network)}><Download size={15}/>Exportar JSON</button><button className="primary" onClick={()=>{setDraft(JSON.stringify(network,null,2));setEditing(!editing)}}><Upload size={15}/>Importar / editar</button></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Ruta</th><th>Recorrido</th><th>Estado</th><th>Última verificación</th><th>Fuente</th></tr></thead><tbody>{network.routes.map(r=><tr key={r.id}><td><RouteBadge route={r}/></td><td>{r.name}<small>{r.stops.length} puntos de ida</small></td><td><span className="pill">{r.status==='demo'?'Demostración':r.status==='authorized'?'Autorizado':r.status==='observed'?'Observado':'Propuesta'}</span></td><td>{r.verified_at||'Pendiente'}</td><td style={{maxWidth:260}}><small>{r.source}</small></td></tr>)}</tbody></table></div>{editing&&<form className="form-stack" style={{marginTop:24}} onSubmit={e=>{e.preventDefault();importNetwork()}}><label>Archivo de red · JSON<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(file){if(file.size>2_000_000){setError('El archivo supera 2 MB.');return}setDraft(await file.text())}}}/></label><label>Revisar contenido<textarea className="editor" value={draft} onChange={e=>setDraft(e.target.value)}/></label><p className="small-note">Cada ruta debe declarar sus puntos de ida y vuelta, geometrías, fuente, estado y fecha de verificación. No se admiten propuestas en la red pública.</p><div className="inline-actions"><button className="primary" disabled={busy||IS_LOCAL_DEMO}><Check size={16}/>{busy?'Validando…':'Validar e importar'}</button><button type="button" className="secondary" onClick={()=>downloadJSON('juliaca-borrador.json',JSON.parse(draft))}><FileJson size={16}/>Descargar borrador</button></div></form>}<div className="analysis-note"><Info size={18}/><div><strong>La fuente acompaña al dato</strong>Un registro autorizado requiere documentación. Un registro observado necesita periodo y condiciones del levantamiento. La ausencia de verificación no demuestra informalidad.</div></div></section>}
 {tab==='reports'&&<section className="surface"><div className="surface-head"><h2>Cola de revisión</h2><span className="pill">{reports.filter(r=>r.status==='pending').length} pendientes</span></div>{reports.length?reports.map(r=><article className="report-item" key={r.id}><div><strong>{r.route_id} · {({route:'Recorrido',fare:'Tarifa',incident:'Incidente',service:'Servicio'} as Record<string,string>)[r.category]}</strong><span className={`pill ${r.status==='reviewed'?'green':''}`}>{r.status==='pending'?'Pendiente':r.status==='reviewed'?'Revisado':'Descartado'}</span></div><p>{r.description}</p>{r.status==='pending'&&<div className="inline-actions"><button className="secondary" onClick={()=>decide(r,'reviewed')}><Check size={15}/>Marcar revisado</button><button className="text-button" onClick={()=>decide(r,'dismissed')}><X size={15}/>Descartar</button></div>}</article>):<div className="empty-state"><Flag size={35}/><h3>No hay reportes pendientes</h3><p>Los reportes enviados desde las fichas de ruta aparecerán aquí.</p></div>}</section>}
 {tab==='gps'&&<section className="surface"><div className="surface-head"><div><h2>Posiciones de vehículos</h2></div><span className="pill">{positions.filter(p=>isFresh(p)).length} posiciones vigentes</span></div>{positions.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Unidad</th><th>Ruta</th><th>Recibida</th><th>Estado</th></tr></thead><tbody>{positions.map(p=><tr key={p.vehicle_id}><td>{p.vehicle_id}</td><td>{p.route_id} · {p.direction?'vuelta':'ida'}</td><td>{new Date(p.timestamp).toLocaleString('es-PE')}</td><td>{p.simulated?'Simulada':isFresh(p)?'Vigente':'Desactualizada'}</td></tr>)}</tbody></table></div>:<div className="empty-state"><Radio size={38}/><h3>Preparado para conectar operadores</h3><p>Primero hay que confirmar el proveedor, el acceso permitido a sus posiciones y la correspondencia entre unidades, rutas y sentidos.</p></div>}<div className="analysis-note"><Info size={18}/><div><strong>De la posición a una llegada confiable</strong>El servidor acepta posiciones normalizadas, descarta fechas futuras y retira del mapa las que superan 90 segundos. Las llegadas permanecerán desactivadas hasta contar con históricos y una validación en campo.</div></div></section>}
 </>{error&&<p className="form-error" role="alert">{error}</p>}</main>
}
