import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.goto('/');await expect(page.locator('.app-shell')).toHaveAttribute('data-ready','true');await expect(page.locator('.app-shell')).toHaveAttribute('data-ready','true')});
test('viajar, guardar, revisar y comparar',async({page})=>{
 await page.goto('/');await expect(page.locator('.app-shell')).toHaveAttribute('data-ready','true');await expect(page.getByRole('heading',{name:'¿A dónde quieres ir?'})).toBeVisible();
 await page.getByLabel('Hasta',{exact:true}).fill('Aeropuerto Inca Manco Cápac');await page.getByRole('option',{name:/Aeropuerto Inca Manco Cápac/}).first().click();await page.getByRole('button',{name:'Buscar mi ruta'}).click();await expect(page.getByRole('heading',{name:'Opciones para tu viaje'})).toBeVisible();await expect(page.getByText('Tu viaje, paso a paso')).toBeVisible();
 await page.getByRole('button',{name:'Rutas',exact:true}).click();await page.getByRole('button',{name:'Guardar D01',exact:true}).click();await page.getByRole('button',{name:'Rutas guardadas',exact:true}).click();await expect(page.getByText('Corredor norte–sur',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:/D01 Corredor norte/}).click();await page.getByRole('button',{name:'Vuelta',exact:true}).click();await expect(page.locator('.stop-timeline li').first()).toContainText('Salida a Puno');
 await page.getByRole('button',{name:'Reportar un cambio'}).click();await page.getByLabel('Descripción',{exact:true}).fill('Prueba de cambio de recorrido para revisión.');await page.getByRole('button',{name:'Enviar a revisión'}).click();await expect(page.getByRole('status')).toContainText('registrado');
 await page.getByRole('button',{name:'Administrar plataforma'}).click();await page.getByRole('button',{name:/^Reportes/}).click();await expect(page.getByText('Prueba de cambio de recorrido para revisión.')).toBeVisible();await page.getByRole('button',{name:'Marcar revisado'}).click();await expect(page.getByText('Revisado',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Observatorio',exact:true}).click();await page.getByRole('tab',{name:'Escenarios'}).click();await page.getByRole('button',{name:'Comparar propuesta'}).click();await expect(page.getByText('Tiempo medio',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Guardar escenario'}).click();await expect(page.locator('.saved-scenario')).toHaveCount(1);
});
test('ubicación denegada y ausencia de servicio',async({page,context})=>{
 await context.clearPermissions();await page.goto('/');await expect(page.locator('.app-shell')).toHaveAttribute('data-ready','true');await page.getByRole('button',{name:'Usar mi ubicación'}).click();await expect(page.getByRole('alert')).toContainText('ubicación');await page.getByLabel('Hasta',{exact:true}).fill('Aeropuerto Inca Manco Cápac');await page.getByLabel('Hora de salida en Perú').fill('02:00');await page.getByRole('button',{name:'Buscar mi ruta'}).click();await expect(page.getByRole('heading',{name:'Sin rutas disponibles'})).toBeVisible();
});
test('registro de campo persiste al recargar',async({page})=>{
 await page.goto('/');await expect(page.locator('.app-shell')).toHaveAttribute('data-ready','true');await page.getByRole('button',{name:'Observatorio',exact:true}).click();await page.getByRole('tab',{name:'Trabajo de campo'}).click();await page.getByLabel('Fecha y hora · Perú').fill('2026-09-06T10:00');await page.getByLabel('Pasajeros contados').fill('15');await page.getByLabel('Vehículos contados').fill('3');await page.getByLabel('Fuente o equipo').fill('Equipo de prueba');await page.getByRole('button',{name:'Guardar observación'}).click();await expect(page.getByText('15 pasajeros · 3 vehículos · 30 min')).toBeVisible();await page.reload();await expect(page.locator('.app-shell')).toHaveAttribute('data-ready','true');await page.getByRole('button',{name:'Observatorio',exact:true}).click();await page.getByRole('tab',{name:'Trabajo de campo'}).click();await expect(page.getByText('15 pasajeros · 3 vehículos · 30 min')).toBeVisible();
});
test('capturas y ausencia de desbordamiento',async({page})=>{
 await page.setViewportSize({width:1440,height:960});await page.goto('/');await expect(page.locator('.app-shell')).toHaveAttribute('data-ready','true');await expect(page.locator('.maplibregl-canvas')).toBeVisible();await page.waitForTimeout(3000);await page.screenshot({path:'../artifacts/desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Observatorio',exact:true}).click();await page.screenshot({path:'../artifacts/analytics.png',fullPage:true});
 for(const width of [320,375,414,768]){await page.setViewportSize({width,height:900});await page.getByRole('button',{name:'Viajar',exact:true}).click();await expect(page.getByRole('heading',{name:'¿A dónde quieres ir?'})).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);expect(overflow).toBe(false);if(width===375)await page.screenshot({path:'../artifacts/mobile.png',fullPage:true})}
});
